version: '3.7'
services: 
    db:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      volumes:
        -  ./data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: 123456
        POSTGRES_USER: postgres
        POSTGRES_DB: Advance


    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
