# Generated by Django 4.2.4 on 2023-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_alter_news_content_alter_product_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
