# Generated by Django 4.2.4 on 2023-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_name',
            field=models.CharField(default='ADVANCEPROJECT', max_length=255),
            preserve_default=False,
        ),
    ]
