# Generated by Django 4.2.4 on 2023-10-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shopproduct_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProduct',
        ),
    ]
