# Generated by Django 4.2.4 on 2023-10-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_brands_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
