# Generated by Django 4.2.4 on 2023-10-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tag_alter_brands_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
