# Generated by Django 4.2.4 on 2023-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
