# Generated by Django 4.2.4 on 2023-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
