# Generated by Django 4.2.4 on 2023-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_aboutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
