# Generated by Django 4.2.4 on 2023-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
    ]
