# Generated by Django 4.2.4 on 2023-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_image_2_product_image_3_product_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
